name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
      working-directory: ./e2e
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./e2e
    - name: Serve Files
      uses: Eun/http-server-action@v1
      with:
        directory: ./poc/frontend
        port: 8080
        no-cache: true
        index-files: |
          ["index.html"]
        allowed-methods: |
          ["GET", "HEAD"]
        content-types: |
          {
            "css": "text/css",
            "html": "text/html",
            "js": "text/javascript",
            "json": "application/json"
          }
        log: "log.txt"
        logTime: "false"
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: ./e2e
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: ./e2e/playwright-report/
        retention-days: 30
